# Docker
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Analyze
  displayName: Analyze sourcecode
  jobs:
  - job: Analyze
    displayName: Analyze job
    pool:
      vmImage: ubuntu-latest
    variables:
      - name: NODE_OPTIONS
        value: --use-openssl-ca
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'sqplayground'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'devops-test'
# SQ project token 224a43a7e58c864b5ddcf797c03bf1e54364ffea
    - task: SonarQubeAnalyze@4

    # Publish Quality Gate Result task
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/bonus/Dockerfile'
        tags: |
          $(tag)
